### ISSUE TITLE
Loading G-Music Library

### ISSUE THREAD

**Issue by johnriggz** [fuzeman/GoogleMusicScrobbler#22]
When I have GoogleMusicScrobbler enabled my library won't load in Google Music. As soon as I click "My Music" a progress bar appears, but never makes any progress and my library never loads.
If I disable GoogleMusicScrobbler my Library loads quickly and without fail. If I re-enable the addon the same behavior returns.

FF 28.0, OS X 10.9.2.

**EDIT**
Also the same behavior under FF 29.0

**Comment by mrgar** [comment]
Have you tested newest version of Firefox to see if the problem remains?
