### ISSUE TITLE
Instalation issue

### ISSUE THREAD

**Issue by Cancerbro** [fuzeman/GoogleMusicScrobbler#31]
I just can't figure out how to install this as a firefox extention

**Comment by fuzeman** [comment]
**1** - Download the latest xpi from https://github.com/fuzeman/GoogleMusicScrobbler/releases

![](http://i.imgur.com/iC9ygNW.png)

**2** - Allow the installation

![](https://i.imgur.com/8R8M6kg.png)

**3** - Click "Install Now"

![](http://i.imgur.com/L8J1pH8.png)

**4** - Open (or refresh) Google Music

**5** - Configuration options will be located inside the Google Music settings page

![](https://i.imgur.com/uX45LBK.png)
