### ISSUE TITLE
Add-on signing

### ISSUE THREAD

**Issue by PerfectSlayer** [fuzeman/GoogleMusicScrobbler#33]
Hi,

I saw you won't update your add-on on AMO any more.
How will you deal with add-on signing?
See more details here: https://wiki.mozilla.org/Addons/Extension_Signing

Thanks!

**Comment by fuzeman** [comment]
The latest release is signed ([v0.8.6.2-beta](https://github.com/fuzeman/GoogleMusicScrobbler/releases/tag/0.8.6.2-beta)).

 Future releases will be added to the development channel on [AMO](https://addons.mozilla.org/en-US/firefox/addon/google-music-scrobbler/) so they can be signed.

**Comment by PerfectSlayer** [comment]
Ok, thanks for the tip!

**Comment by PerfectSlayer** [comment]
Another question: did you consider using updateUrl ?
I was missing the last update =(

**Comment by fuzeman** [comment]
> Another question: did you consider using updateUrl ?

Will look into this *(next week)*, shouldn't be too hard to implement.
