### ISSUE TITLE
settings section doesn't show up in 0.8.6.2-beta

### ISSUE THREAD

**Issue by slang800** [fuzeman/GoogleMusicScrobbler#34]
![1438921041](https://cloud.githubusercontent.com/assets/1049204/9128633/defbb7e2-3c99-11e5-9df7-244e5a8cd430.png)

just gives some errors & refuses to show up. after refreshing the page a couple times, the link account button did show up once, but it wasn't clickable

**Comment by lucasoutloud** [comment]
Came here to write that I've experienced the same issue.

**Comment by fuzeman** [comment]
Looking at this issue now.

Strangely, I can see the settings but scrobbling isn't working anymore..

**Comment by fuzeman** [comment]
I've fixed scrobbling in **[v0.8.6.3-beta](https://github.com/fuzeman/GoogleMusicScrobbler/releases/tag/0.8.6.3-beta)**, let me know if the settings aren't displayed still *(can't reproduce this issue on my system)*.

**Comment by lucasoutloud** [comment]
@fuzeman the new beta fixes the issue. Thanks so much!
