### ISSUE TITLE
Not scrobbling in Firefox 40 on OS X Yosemite 10.10.4

### ISSUE THREAD

**Issue by shadrach** [fuzeman/GoogleMusicScrobbler#35]
Just installed in Firefox 40 on MacBook running OS X Yosemite 10.10.4, however nothing seems to be scrobbling to last.fm. I previously had a different scrobbling service (http://www.danielslaughter.com/projects/google-music-with-lastfm/), but have since removed greasemonkey and the script it was running. 
* Google Music Scrobbler Extension was successfully linked to last.fm account (message in settings next to Google Music Scrobbler button "Unlink Account" indicates "Currently linked with account")
* Display status icon selected = red icon appearing correctly in Google Play menu

Console after four songs:
```
GMS-PS Object { Xx: false, yv: Array[2], $o: Object, Aya: Object, b0: null, kB: Object, xc: Object, Ec: Object, ax: null, LF: Object, 1 more… } Array [ Object, true, false, Object ] page.js:57:17
GMS-PS Object { Xx: false, yv: Array[2], $o: Object, Aya: Object, b0: null, kB: Object, xc: Object, Ec: Object, ax: null, LF: Object, 1 more… } Array [ Object, false, false, Object ] page.js:57:17
GMS-PS Object { Xx: false, yv: Array[2], $o: Object, Aya: Object, b0: null, kB: Object, xc: Object, Ec: Object, ax: null, LF: Object, 1 more… } Array [ Object, false, false, Object ] page.js:57:17
GMS-PS Object { Xx: false, yv: Array[2], $o: Object, Aya: Object, b0: null, kB: Object, xc: Object, Ec: Object, ax: null, LF: Object, 1 more… } Array [ Object, false, false, Object ] page.js:57:17
POST XHR https://ws.audioscrobbler.com/2.0/ [HTTP/1.1 403 Forbidden 223ms]
```

**Comment by maturano** [comment]
I'm just switching to Mac and I have the same issue.

Firefox 49.0
OS X El Capitan 10.11.6

**Comment by shadrach** [comment]
Hey Maturano, I solved this by using the .xpi from Github, and *not* the Firefox extension (https://addons.mozilla.org/en-US/firefox/addon/google-music-scrobbler/).

Try grabbing the latest version from here instead: https://github.com/fuzeman/GoogleMusicScrobbler/releases
