### ISSUE TITLE
settings section doesn't show up in 0.8.6.4-beta-signed

### ISSUE THREAD

**Issue by bcsopi** [fuzeman/GoogleMusicScrobbler#36]
![capture](https://cloud.githubusercontent.com/assets/11555574/10715053/d4218322-7b07-11e5-981a-3a03a8bac81a.PNG)
![capture2](https://cloud.githubusercontent.com/assets/11555574/10715054/d45cc36a-7b07-11e5-9e55-f2c3477aa105.PNG)
Whatever I do, refreshing the page, clearing cache, the section won't show up...

**Comment by fuzeman** [comment]
Should have some time to look at this tomorrow.

**Comment by fuzeman** [comment]
Fixed in **[v0.8.6.5-beta](https://github.com/fuzeman/GoogleMusicScrobbler/releases/tag/0.8.6.5-beta)**

**Comment by bcsopi** [comment]
Thank You, You're awesome! :)
