### ISSUE TITLE
Scrobbling with 0.8.6.5-beta stopped working

### ISSUE THREAD

**Issue by marado** [fuzeman/GoogleMusicScrobbler#37]
Yesterday (and previous days) it was working, today it isn't, so I am sort of assuming something changed on Google's side.

Browser: Firefox 38.4

**Comment by sergeytunnik** [comment]
I also confirm. Last scrobbling for my account was on the 1st of December.
Firefox 42.0

**Comment by fuzeman** [comment]
Will have a look this weekend, normally it's a fairly simple fix.

**Comment by fuzeman** [comment]
Fixed in **[v0.8.6.6-beta](https://github.com/fuzeman/GoogleMusicScrobbler/releases/tag/0.8.6.6-beta)**

**Comment by marado** [comment]
Works fine, thanks!
