### ISSUE TITLE
Google Music Scrobbler will not be available in Firefox 44+

### ISSUE THREAD

**Issue by smeggysmeg** [fuzeman/GoogleMusicScrobbler#38]
As of [Mozilla Firefox 44](https://wiki.mozilla.org/Add-ons/Extension_Signing), extension signing via uploading to Addons.Mozilla.Org (AMO) will be a requirement for extensions to function in Firefox. They will be eliminating the about:config flag allowing the installation of unsigned extensions.

Will you return to updating the version of Google Music Scrobbler on AMO?

**Comment by fuzeman** [comment]
Signed versions of the addon have been available on the [releases](https://github.com/fuzeman/GoogleMusicScrobbler/releases) page for awhile. You can also install the "Development Channel" on the AMO [page](https://addons.mozilla.org/en-US/firefox/addon/google-music-scrobbler/) for the latest version of the addon *(all new versions of the addon will be uploaded to the development channel)*.

The addon will likely be reviewed again (and properly released) after an overhaul later this year :smile:
