### ISSUE TITLE
Won't link to last.fm any more

### ISSUE THREAD

**Issue by benshep** [fuzeman/GoogleMusicScrobbler#39]
On Firefox 48.0.2 (latest) on Windows 7. Got GMS 0.9.0-beta (latest).

I click 'Link account', authorise it on the Last.fm page (this seems to take 2-3 attempts for some reason), and click 'Confirm link', but it sticks on 'Checking authorization status...'. I'm behind a firewall but presumably Firefox knows about that. Any thoughts?

**Comment by fuzeman** [comment]
I think the Last.fm API was down around the time this issue was created, is it working now?

**Comment by benshep** [comment]
Yes, it's fine now. Thanks!
