### ISSUE TITLE
 Mark as multiprocess compat

### ISSUE THREAD

**Issue by ejstacey** [fuzeman/GoogleMusicScrobbler#40]
Need to mark compatible with multiprocess.  It seems this works fine in multiprocess. - https://blog.mozilla.org/addons/2016/08/02/multi-process-firefox-and-add-ons-a-call-to-action/

in package.json permission: { multiprocess: true }

https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/package_json#Key_reference

**Comment by fuzeman** [comment]
The latest release ([v0.10.1-beta](https://github.com/fuzeman/GoogleMusicScrobbler/releases/tag/0.10.1-beta)) has been marked as multiprocess compatible. Thanks for letting me know about this :smile:
